/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as StudentRouteImport } from './routes/_student'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminAuthenticatedRouteImport } from './routes/admin/_authenticated'
import { Route as StudentSettingsRouteImport } from './routes/_student/settings'
import { Route as StudentProfileRouteImport } from './routes/_student/profile'
import { Route as StudentNotesDeadlinesRouteImport } from './routes/_student/notes-deadlines'
import { Route as StudentHomeRouteImport } from './routes/_student/home'
import { Route as StudentDiscussionsRouteImport } from './routes/_student/discussions'
import { Route as AdminAuthenticatedIndexRouteImport } from './routes/admin/_authenticated/index'
import { Route as AdminAuthenticatedStudentsRouteImport } from './routes/admin/_authenticated/students'
import { Route as AdminAuthenticatedNewsRouteImport } from './routes/admin/_authenticated/news'
import { Route as AdminAuthenticatedEventsRouteImport } from './routes/admin/_authenticated/events'
import { Route as AdminAuthenticatedDiscussionsRouteImport } from './routes/admin/_authenticated/discussions'
import { Route as StudentProfileProfileIdRouteImport } from './routes/_student/profile_.$profileId'
import { Route as StudentNewsNewsIdRouteImport } from './routes/_student/news.$newsId'
import { Route as StudentEventsEventIdRouteImport } from './routes/_student/events.$eventId'
import { Route as StudentDiscussionsDiscussionIdRouteImport } from './routes/_student/discussions_.$discussionId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/_student',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuthenticatedRoute = AdminAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => AdminRouteRoute,
} as any)
const StudentSettingsRoute = StudentSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentNotesDeadlinesRoute = StudentNotesDeadlinesRouteImport.update({
  id: '/notes-deadlines',
  path: '/notes-deadlines',
  getParentRoute: () => StudentRoute,
} as any)
const StudentHomeRoute = StudentHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => StudentRoute,
} as any)
const StudentDiscussionsRoute = StudentDiscussionsRouteImport.update({
  id: '/discussions',
  path: '/discussions',
  getParentRoute: () => StudentRoute,
} as any)
const AdminAuthenticatedIndexRoute = AdminAuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAuthenticatedRoute,
} as any)
const AdminAuthenticatedStudentsRoute =
  AdminAuthenticatedStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedNewsRoute = AdminAuthenticatedNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AdminAuthenticatedRoute,
} as any)
const AdminAuthenticatedEventsRoute =
  AdminAuthenticatedEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const AdminAuthenticatedDiscussionsRoute =
  AdminAuthenticatedDiscussionsRouteImport.update({
    id: '/discussions',
    path: '/discussions',
    getParentRoute: () => AdminAuthenticatedRoute,
  } as any)
const StudentProfileProfileIdRoute = StudentProfileProfileIdRouteImport.update({
  id: '/profile_/$profileId',
  path: '/profile/$profileId',
  getParentRoute: () => StudentRoute,
} as any)
const StudentNewsNewsIdRoute = StudentNewsNewsIdRouteImport.update({
  id: '/news/$newsId',
  path: '/news/$newsId',
  getParentRoute: () => StudentRoute,
} as any)
const StudentEventsEventIdRoute = StudentEventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => StudentRoute,
} as any)
const StudentDiscussionsDiscussionIdRoute =
  StudentDiscussionsDiscussionIdRouteImport.update({
    id: '/discussions_/$discussionId',
    path: '/discussions/$discussionId',
    getParentRoute: () => StudentRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminAuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/discussions': typeof StudentDiscussionsRoute
  '/home': typeof StudentHomeRoute
  '/notes-deadlines': typeof StudentNotesDeadlinesRoute
  '/profile': typeof StudentProfileRoute
  '/settings': typeof StudentSettingsRoute
  '/admin/login': typeof AdminLoginRoute
  '/discussions/$discussionId': typeof StudentDiscussionsDiscussionIdRoute
  '/events/$eventId': typeof StudentEventsEventIdRoute
  '/news/$newsId': typeof StudentNewsNewsIdRoute
  '/profile/$profileId': typeof StudentProfileProfileIdRoute
  '/admin/discussions': typeof AdminAuthenticatedDiscussionsRoute
  '/admin/events': typeof AdminAuthenticatedEventsRoute
  '/admin/news': typeof AdminAuthenticatedNewsRoute
  '/admin/students': typeof AdminAuthenticatedStudentsRoute
  '/admin/': typeof AdminAuthenticatedIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminAuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/discussions': typeof StudentDiscussionsRoute
  '/home': typeof StudentHomeRoute
  '/notes-deadlines': typeof StudentNotesDeadlinesRoute
  '/profile': typeof StudentProfileRoute
  '/settings': typeof StudentSettingsRoute
  '/admin/login': typeof AdminLoginRoute
  '/discussions/$discussionId': typeof StudentDiscussionsDiscussionIdRoute
  '/events/$eventId': typeof StudentEventsEventIdRoute
  '/news/$newsId': typeof StudentNewsNewsIdRoute
  '/profile/$profileId': typeof StudentProfileProfileIdRoute
  '/admin/discussions': typeof AdminAuthenticatedDiscussionsRoute
  '/admin/events': typeof AdminAuthenticatedEventsRoute
  '/admin/news': typeof AdminAuthenticatedNewsRoute
  '/admin/students': typeof AdminAuthenticatedStudentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/_student': typeof StudentRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_student/discussions': typeof StudentDiscussionsRoute
  '/_student/home': typeof StudentHomeRoute
  '/_student/notes-deadlines': typeof StudentNotesDeadlinesRoute
  '/_student/profile': typeof StudentProfileRoute
  '/_student/settings': typeof StudentSettingsRoute
  '/admin/_authenticated': typeof AdminAuthenticatedRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/_student/discussions_/$discussionId': typeof StudentDiscussionsDiscussionIdRoute
  '/_student/events/$eventId': typeof StudentEventsEventIdRoute
  '/_student/news/$newsId': typeof StudentNewsNewsIdRoute
  '/_student/profile_/$profileId': typeof StudentProfileProfileIdRoute
  '/admin/_authenticated/discussions': typeof AdminAuthenticatedDiscussionsRoute
  '/admin/_authenticated/events': typeof AdminAuthenticatedEventsRoute
  '/admin/_authenticated/news': typeof AdminAuthenticatedNewsRoute
  '/admin/_authenticated/students': typeof AdminAuthenticatedStudentsRoute
  '/admin/_authenticated/': typeof AdminAuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/register'
    | '/discussions'
    | '/home'
    | '/notes-deadlines'
    | '/profile'
    | '/settings'
    | '/admin/login'
    | '/discussions/$discussionId'
    | '/events/$eventId'
    | '/news/$newsId'
    | '/profile/$profileId'
    | '/admin/discussions'
    | '/admin/events'
    | '/admin/news'
    | '/admin/students'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/register'
    | '/discussions'
    | '/home'
    | '/notes-deadlines'
    | '/profile'
    | '/settings'
    | '/admin/login'
    | '/discussions/$discussionId'
    | '/events/$eventId'
    | '/news/$newsId'
    | '/profile/$profileId'
    | '/admin/discussions'
    | '/admin/events'
    | '/admin/news'
    | '/admin/students'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/_student'
    | '/login'
    | '/register'
    | '/_student/discussions'
    | '/_student/home'
    | '/_student/notes-deadlines'
    | '/_student/profile'
    | '/_student/settings'
    | '/admin/_authenticated'
    | '/admin/login'
    | '/_student/discussions_/$discussionId'
    | '/_student/events/$eventId'
    | '/_student/news/$newsId'
    | '/_student/profile_/$profileId'
    | '/admin/_authenticated/discussions'
    | '/admin/_authenticated/events'
    | '/admin/_authenticated/news'
    | '/admin/_authenticated/students'
    | '/admin/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  StudentRoute: typeof StudentRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_student': {
      id: '/_student'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/_authenticated': {
      id: '/admin/_authenticated'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAuthenticatedRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_student/settings': {
      id: '/_student/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof StudentSettingsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/profile': {
      id: '/_student/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/notes-deadlines': {
      id: '/_student/notes-deadlines'
      path: '/notes-deadlines'
      fullPath: '/notes-deadlines'
      preLoaderRoute: typeof StudentNotesDeadlinesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/home': {
      id: '/_student/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof StudentHomeRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/discussions': {
      id: '/_student/discussions'
      path: '/discussions'
      fullPath: '/discussions'
      preLoaderRoute: typeof StudentDiscussionsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/_authenticated/': {
      id: '/admin/_authenticated/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAuthenticatedIndexRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/students': {
      id: '/admin/_authenticated/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminAuthenticatedStudentsRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/news': {
      id: '/admin/_authenticated/news'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AdminAuthenticatedNewsRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/events': {
      id: '/admin/_authenticated/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminAuthenticatedEventsRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/admin/_authenticated/discussions': {
      id: '/admin/_authenticated/discussions'
      path: '/discussions'
      fullPath: '/admin/discussions'
      preLoaderRoute: typeof AdminAuthenticatedDiscussionsRouteImport
      parentRoute: typeof AdminAuthenticatedRoute
    }
    '/_student/profile_/$profileId': {
      id: '/_student/profile_/$profileId'
      path: '/profile/$profileId'
      fullPath: '/profile/$profileId'
      preLoaderRoute: typeof StudentProfileProfileIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/news/$newsId': {
      id: '/_student/news/$newsId'
      path: '/news/$newsId'
      fullPath: '/news/$newsId'
      preLoaderRoute: typeof StudentNewsNewsIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/events/$eventId': {
      id: '/_student/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof StudentEventsEventIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/discussions_/$discussionId': {
      id: '/_student/discussions_/$discussionId'
      path: '/discussions/$discussionId'
      fullPath: '/discussions/$discussionId'
      preLoaderRoute: typeof StudentDiscussionsDiscussionIdRouteImport
      parentRoute: typeof StudentRoute
    }
  }
}

interface AdminAuthenticatedRouteChildren {
  AdminAuthenticatedDiscussionsRoute: typeof AdminAuthenticatedDiscussionsRoute
  AdminAuthenticatedEventsRoute: typeof AdminAuthenticatedEventsRoute
  AdminAuthenticatedNewsRoute: typeof AdminAuthenticatedNewsRoute
  AdminAuthenticatedStudentsRoute: typeof AdminAuthenticatedStudentsRoute
  AdminAuthenticatedIndexRoute: typeof AdminAuthenticatedIndexRoute
}

const AdminAuthenticatedRouteChildren: AdminAuthenticatedRouteChildren = {
  AdminAuthenticatedDiscussionsRoute: AdminAuthenticatedDiscussionsRoute,
  AdminAuthenticatedEventsRoute: AdminAuthenticatedEventsRoute,
  AdminAuthenticatedNewsRoute: AdminAuthenticatedNewsRoute,
  AdminAuthenticatedStudentsRoute: AdminAuthenticatedStudentsRoute,
  AdminAuthenticatedIndexRoute: AdminAuthenticatedIndexRoute,
}

const AdminAuthenticatedRouteWithChildren =
  AdminAuthenticatedRoute._addFileChildren(AdminAuthenticatedRouteChildren)

interface AdminRouteRouteChildren {
  AdminAuthenticatedRoute: typeof AdminAuthenticatedRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAuthenticatedRoute: AdminAuthenticatedRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface StudentRouteChildren {
  StudentDiscussionsRoute: typeof StudentDiscussionsRoute
  StudentHomeRoute: typeof StudentHomeRoute
  StudentNotesDeadlinesRoute: typeof StudentNotesDeadlinesRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentSettingsRoute: typeof StudentSettingsRoute
  StudentDiscussionsDiscussionIdRoute: typeof StudentDiscussionsDiscussionIdRoute
  StudentEventsEventIdRoute: typeof StudentEventsEventIdRoute
  StudentNewsNewsIdRoute: typeof StudentNewsNewsIdRoute
  StudentProfileProfileIdRoute: typeof StudentProfileProfileIdRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentDiscussionsRoute: StudentDiscussionsRoute,
  StudentHomeRoute: StudentHomeRoute,
  StudentNotesDeadlinesRoute: StudentNotesDeadlinesRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentSettingsRoute: StudentSettingsRoute,
  StudentDiscussionsDiscussionIdRoute: StudentDiscussionsDiscussionIdRoute,
  StudentEventsEventIdRoute: StudentEventsEventIdRoute,
  StudentNewsNewsIdRoute: StudentNewsNewsIdRoute,
  StudentProfileProfileIdRoute: StudentProfileProfileIdRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  StudentRoute: StudentRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
